services:
  db:
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    image: mysql:latest
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
  wp:
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wp
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=wp
      - WORDPRESS_DEBUG='1'
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./dist:/var/www/html/wp-content/themes/wp-theme-starter
volumes:
  db_data:
